### ISSUE TITLE
Request: Ability to specify output filename and path.

### ISSUE THREAD

**Issue by MichaelTiernan** [kencormack/system_info#4]
I'd be real handy to be able to specify the filename (and/or path) used for the output.
Even if it was a *partial* specification it would be very helpful.

**Comment by kencormack** [comment]
Hello, Michael -

Perhaps.  Let me think on this a bit, to figure how best to go about it, if at all.  With the holiday right on top of us, it may take a few days, given distractions.

Ken

**Comment by MichaelTiernan** [comment]
> Perhaps. Let me think on this a bit, to figure how best to go about it, if at all.
> With the holiday right on top of us, it may take a few days, given distractions.

Good grief! No! Just put it on the list and enjoy your holiday!
It's not an 'issue' but a 'would be nice' item.
If it's going to happen it will. :)

**Comment by kencormack** [comment]
Hello, Michael -

The feature has been added to version 3.0.2.  See the CHANGE_LOG for details.
I will go ahead and close this out.

Ken

**Comment by kencormack** [comment]
Requested feature implemented in 3.0.2
